#security:
#  basic:
#    enabled: true
#  user:
#    name: discovery
#    password: 3GfhPZQifTpVcu
    
server:
  port: 7003
eureka:
#  自我保护机制 
#  server:
#    enable-self-preservation: false
  instance:
    hostname: eureka7003
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/